# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('app_fu_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='MyCollects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amovies.Movies')),
            ],
            options={
                'db_table': 'MyCollects',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('u_password', models.CharField(max_length=50)),
                ('u_icons', models.ImageField(upload_to='icons')),
                ('u_email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='mycollects',
            name='m_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amovies.Users'),
        ),
    ]
